spring:
  application:
  name: crowdfunding

    #configuration for postgreSQL database
  datasource:
    url: jdbc:postgresql://localhost:5432/crowdfunding
    username: ${pgUsername}
    password: ${pgPassword}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true

    hibernate:
        ddl-auto: update

  jwt-secret: ${jwt_secretKey}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  project:
    file: uploads/

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail_username}
    password: ${gmail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  redis:
    host: localhost
    port: 6379
    client-type: jedis
#   password: ${REDIS_PASSWORD}
